---
- name: Install and start apache
  hosts: all
  become: yes
  tasks:

  - name: Install apache
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: Install firewalld
    ansible.builtin.dnf:
      name: firewalld
      state: present

  - name: Start firewalld
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: true
    check_mode: false
  
  - name: Permit traffic in default zone for http service
    ansible.builtin.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: true
    check_mode: false
     
  - name: Start apache
    ansible.builtin.service:
      name: httpd
      state: started
    check_mode: false
  - name: Copy index.html
    ansible.builtin.copy:
      src: web.html
      dest: /var/www/html/index.html
      mode: '644'
