---
- name: Basic System Setup
  hosts: all
  become: true
  tasks:

    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow HTTP traffic on web servers
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
      notify: Reload Firewall

    - name: Allow HTTPS traffic on web servers
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
      notify: Reload Firewall

  handlers:
    - name: Reload Firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded
    
    - name: Install apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start apache
      ansible.builtin.service:
        name: httpd
        state: started
      check_mode: false

    - name: Copy index.html
      ansible.builtin.copy:
        src: web.html
        dest: /var/www/html/index.html
        mode: '644'

    - name: Create webapp service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: cody-service
            namespace: summit-edu
          spec:
            selector:
              env: cody
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create webapp route
      kubernetes.core.k8s:
        state: present
        definition: 
          kind: Route
          apiVersion: route.openshift.io/v1
          metadata:
            name: cody-route
            namespace: summit-edu
            labels: {}
          spec:
            to:
              kind: Service
              name: cody-service
            tls:
              termination: edge
              insecureEdgeTerminationPolicy: Redirect
            wildcardPolicy: None
            port:
              targetPort: 80