- name: Create Service and Route for our Apache Webserver
  hosts: all
  tasks:

  - name: Create webapp route
    kubernetes.core.k8s:
      state: present
      definition: 
        kind: Route
        apiVersion: route.openshift.io/v1
        metadata:
          name: cody-route
          namespace: summit-edu
          labels: {}
        spec:
          to:
            kind: Service
            name: cody-service
          tls: null
          port:
            targetPort: 80
