- name: Create Service and Route for webserver
  hosts: all

  tasks:
    - name: Expose https port with ClusterIP using spec
      kubernetes.core.k8s_service:
        state: present
        name: webapp
        namespace: openshift-cnv
        inline:
          spec:
            ports:
            - port: 443
              protocol: TCP
            selector:
              key: special
