- name: Create Service and Route for our Apache Webserver
  hosts: all

  tasks:
    - name: Create webapp service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: webapp
            namespace: openshift-cnv
          spec:
            selector:
              env: webapp
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80

    - name: Create webapp route
      kubernetes.core.k8s:
        state: present
        definition: 
          

    - name: Create webapp Route
      
