- name: Create Service and Route for our Apache Webserver
  hosts: all
  tasks:

  - name: Create webapp route
    kubernetes.core.k8s:
      state: present
      definition: 
        kind: Route
        apiVersion: route.openshift.io/v1
        metadata:
          name: summit-edu-route
          namespace: summit-edu
          labels: {}
        spec:
          to:
            kind: Service
            name: summit-edu-service
          tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect
          wildcardPolicy: None
          port:
            targetPort: 80
