---
- name: Basic System Setup
  hosts: all
  become: true
  tasks:

    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Ensure firewalld is running
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: Allow HTTPS traffic on web servers
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
      notify: Reload Firewall

  handlers:
    - name: Reload Firewall
      ansible.builtin.service:
        name: firewalld
        state: reloaded